### ISSUE TITLE
makeprior

### ISSUE THREAD

**Issue by isisarantes** [meganlsmith/delimitR-manual#4]
Hi Megan,

I'm doing the tutorial before using my data. When I ran the command line below I got an error message. 
FullPrior <- makeprior(prefix=obsprefix,
                       nspec=obsspecies,
                       nclasses=nclasses,
                       getwd(),
                       traitsfile = traitsfile,
                       threshold=100, 
                       thefolder = 'Prior',
                       ncores = 2)
                       
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.

Not sure how it fix it. Any idea?
Cheers
Ísis

**Comment by meganlsmith** [comment]
Hi Isis,
I haven't seen this error before. Can you let me know a) the operating
system and version you are using (e.g. OSX 10.13.6), the version of R
you're using, and the version of python you're using?
Best,
Megan
Megan L. Smith, PhD
Department of Evolution, Ecology, & Organismal Biology
300 Aronoff Labs
The Ohio State University
318 W. 12th Avenue
Columbus, OH 43210-1293

**Comment by isisarantes** [comment]
Hi Megan,

a) macOS Catalina version 10.15.4
b) R version 3.6.3 (2020-02-29) "Holding the Windsock"

I changed the number of cores to 1 and it fixed the issue (ncores = 1). 
It's probably something related to OS Catalina but not sure.
Thank you,
Ísis

**Comment by meganlsmith** [comment]
Hi Isis,

Hm, that's odd. Glad it's working, but wish you could use multiple cores.
I'll try to figure this out ASAP. Unfortunately, right now I'm working from
home and don't have access to a computer that can run Catalina, so I may
have some trouble figuring this one out until I'm able to go back into the
office.

Best,
Megan
Megan L. Smith, PhD
Department of Evolution, Ecology, & Organismal Biology
300 Aronoff Labs
The Ohio State University
318 W. 12th Avenue
Columbus, OH 43210-1293
