### ISSUE TITLE
Question about makeprior runtimes

### ISSUE THREAD

**Issue by btmartin721** [meganlsmith/delimitR-manual#6]
Hello Dr. Smith,

I have more of a question than an issue. 

I am trying to run makeprior() for the full prior on a large dataset, with the Processed*.obs files being ~6.2 GB (5 tips). The Binned*.obs files are being written to a lot more slowly (~20 MB in one day, whereas the Processed files were written in a few minutes). Are the binned SFS files usually a lot smaller than the Processes*.obs files? If so I might not need to worry about it.

If not and they will eventually reach several GB in size, it would seemingly take a really long time to finish. If that's the case, is there any way I could speed it up? I am using a low class size of 3 already, and have all models running in parallel at the same time (so it won't need to repeat the whole process again).

The fastsimcoal simulation didn't take too long (~26 hours), so if running it with different priors might speed it up I can try that. I did use some relatively broad population size priors, but I don't know if that's slowing the binning down or not.

Do you have any suggestions? Or is the only option to just wait it out?

Thanks for your time.

-Bradley

**Comment by btmartin721** [comment]
Nevermind. They finished. Sorry :)

**Comment by meganlsmith** [comment]
Hi Bradley,
Glad it worked out! That step can take a while, but the file will
definitely be smaller than the processed file.
Best,
Megan
Megan L. Smith, PhD
NSF Postdoctoral Research Fellow
Department of Biology
Indiana University
